extends: site.yaml
mode: production
media_url: media
publisher:
    mae:
        type: hyde.ext.publishers.pyfs.PyFS
        url: sftp://biosport@mae.ucdavis.edu/home/grads/biosport/public_html/jkm/classes/eng4
